services:
  - type: web
    name: youtube-stream-api
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: ENV
        value: production
      - key: REQUEST_TIMEOUT
        value: 90      - key: COOKIES_FILE
        value: /tmp/cookies.txt
      - key: LOG_DIR
        value: /tmp/proxyLogs